version: '3'
x-common:
  database:
    &database
    MYSQL_DATABASE: database
    MYSQL_ROOT_PASSWORD: "qg&ys946^L8kin*hoU#znDwbPCXU35"

services:
  backend:
    build: .
    ports:
      - "80:5000" # 5000 -> 80
    depends_on:
      - db
    environment:
      <<: *database
  db:
    image: mysql
    environment:
      <<: *database