version: '3.1'

services:
  backend:
    container_name: flask # It gives a significant name to compose container
    restart: unless-stopped # it will restart on crash, unless stopped by cli or ctrl+c
    build: .
    ports:
      - "80:5000" # 5000 -> 80
    depends_on:
      - db
    env_file:
      - .env
      - src/app.env
  db:
    container-name: mysql # It gives a significant name to compose container
    restart: unless-stopped # it will restart on crash, unless stopped by cli or ctrl+c
    image: mysql
    env_file:
      - .env