# PLS DONT CHANGE THIS FILE
services:
  backend:
    image: backend
    build: .
    ports:
      - "80:5000" # 5000 -> 80
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    env_file:
      - .env
  db:
    image: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 1s
      retries: 30
    env_file:
      - .env