version: '3'

services:
  backend:
    build: .
    ports:
      - "80:5000" # 5000 -> 80
    depends_on:
      - db
    env_file:
      - .env
      - src/app.env
  db:
    image: mysql
    env_file:
      - .env